Task
MrAlejandro/rackup pull request #1
Opened 2019-03-30 05:44 UTC by MrAlejandro

2019-03-30 14:36 UTC, BubuntuClu requested changes

2019-03-30 14:36 UTC, BubuntuClu commented on app.rb
> +    handle_request
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2019-03-31 06:51 UTC, MrAlejandro commented on app.rb
> +    handle_request
done

2019-03-31 23:45 UTC, BubuntuClu commented on time_formatter.rb
> +      year: :year,
тут лучше указать строку, которая будет использоваться для нужной части времени в методе `strftime` или напрямую метод `Time.now.year` и т.д.

2019-03-31 23:45 UTC, BubuntuClu commented on app.rb
> +  def respond(result)
`response` обычно используется при ответе на `request`

2019-04-01 09:00 UTC, psylone approved these changes

2019-04-01 09:00 UTC, psylone commented on app.rb
> +    query_params = Rack::Utils.parse_nested_query(@env['QUERY_STRING'])
Используй объект класса `Rack::Request`, в нём есть метод `params`.

2019-04-01 09:00 UTC, psylone commented on time_formatter.rb
> +    unknown_formats.empty? ? successful_result(time_parts) : failed_result(unknown_formats)
Если сделать метод `success?` на основе `unknown_formats.empty?`, то можно будет отказаться от методов `successful_result` и `failed_result`.

2019-04-01 09:00 UTC, psylone commented on app.rb
> +    return respond_not_found if query_params['format'].nil?
По факту, это 400, а не 404, потому что путь (ресурс) был найден.

2019-04-01 09:00 UTC, psylone commented on app.rb
> +    ALLOWED_PATHS.include?(@env['REQUEST_PATH'])
Здесь лучше сделать с помощью `case` поиск пути, поскольку у нас может быть несколько обработчиков URL и для каждого из них хорошо иметь собственный метод обработчик, например: `handle_time_request`.

2019-04-01 16:27 UTC, MrAlejandro commented on time_formatter.rb
> +      year: :year,
done

2019-04-01 16:40 UTC, MrAlejandro commented on app.rb
> +    ALLOWED_PATHS.include?(@env['REQUEST_PATH'])
немного по своему переделал

2019-04-01 16:40 UTC, MrAlejandro commented on app.rb
> +    return respond_not_found if query_params['format'].nil?
done

2019-04-01 16:42 UTC, MrAlejandro commented on app.rb
> +    query_params = Rack::Utils.parse_nested_query(@env['QUERY_STRING'])
done

2019-04-01 16:50 UTC, MrAlejandro commented on time_formatter.rb
> +    unknown_formats.empty? ? successful_result(time_parts) : failed_result(unknown_formats)
не очень понял идею, кто будет вызывать `success?`?

2019-04-02 15:58 UTC, merged